{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "veritas.fullname" . }}-api
  labels:
    {{- include "veritas.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "veritas.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/api/v1/metrics"
      labels:
        {{- include "veritas.api.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "veritas.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "veritas.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: api
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.global.imageRegistry }}{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.api.service.targetPort }}
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ include "veritas.fullname" . }}-config
        - secretRef:
            name: {{ include "veritas.fullname" . }}-secrets
        resources:
          {{- toYaml .Values.api.resources | nindent 12 }}
        livenessProbe:
          {{- toYaml .Values.api.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.api.readinessProbe | nindent 12 }}
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        {{- if .Values.persistence.uploads.enabled }}
        - name: uploads
          mountPath: /app/uploads
        {{- end }}
      volumes:
      - name: logs
        emptyDir: {}
      {{- if .Values.persistence.uploads.enabled }}
      - name: uploads
        persistentVolumeClaim:
          claimName: {{ include "veritas.fullname" . }}-uploads-pvc
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
