# ======================================================================
# VERITAS Framework - ConfigMap
# Application configuration
# ======================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: veritas-config
  namespace: veritas-production
  labels:
    app: veritas
    component: config
data:
  # Application settings
  VERITAS_ENV: "production"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  
  # API settings
  API_VERSION: "v1"
  API_PREFIX: "/api/v1"
  ENABLE_CORS: "true"
  CORS_ORIGINS: "https://veritas.example.com"
  
  # Worker settings
  WORKER_CONCURRENCY: "4"
  WORKER_PREFETCH_MULTIPLIER: "4"
  WORKER_MAX_TASKS_PER_CHILD: "1000"
  
  # Database settings (non-sensitive)
  DB_POOL_SIZE: "20"
  DB_MAX_OVERFLOW: "10"
  DB_POOL_TIMEOUT: "30"
  DB_POOL_RECYCLE: "3600"
  
  # Redis settings (non-sensitive)
  REDIS_MAX_CONNECTIONS: "50"
  REDIS_SOCKET_TIMEOUT: "5"
  REDIS_SOCKET_CONNECT_TIMEOUT: "5"
  
  # Rate limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_DEFAULT: "100/minute"
  RATE_LIMIT_AUTH: "5/minute"
  
  # Session settings
  SESSION_LIFETIME: "3600"  # 1 hour
  SESSION_REFRESH_LIFETIME: "2592000"  # 30 days
  
  # File upload
  MAX_UPLOAD_SIZE: "104857600"  # 100MB
  ALLOWED_EXTENSIONS: ".pdf,.docx,.txt,.md"
  
  # Agent execution
  AGENT_TIMEOUT: "300"  # 5 minutes
  MAX_CONCURRENT_AGENTS: "10"
  
  # Quality settings
  QUALITY_THRESHOLD: "0.7"
  ENABLE_AUTO_REVIEW: "true"
  
  # Monitoring
  METRICS_ENABLED: "true"
  TRACING_ENABLED: "true"
  TRACING_SAMPLE_RATE: "0.1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: veritas-config
  namespace: veritas-staging
  labels:
    app: veritas
    component: config
data:
  # Application settings
  VERITAS_ENV: "staging"
  LOG_LEVEL: "DEBUG"
  LOG_FORMAT: "json"
  
  # API settings
  API_VERSION: "v1"
  API_PREFIX: "/api/v1"
  ENABLE_CORS: "true"
  CORS_ORIGINS: "*"
  
  # Worker settings
  WORKER_CONCURRENCY: "2"
  WORKER_PREFETCH_MULTIPLIER: "4"
  WORKER_MAX_TASKS_PER_CHILD: "1000"
  
  # Database settings (non-sensitive)
  DB_POOL_SIZE: "10"
  DB_MAX_OVERFLOW: "5"
  DB_POOL_TIMEOUT: "30"
  DB_POOL_RECYCLE: "3600"
  
  # Redis settings (non-sensitive)
  REDIS_MAX_CONNECTIONS: "25"
  REDIS_SOCKET_TIMEOUT: "5"
  REDIS_SOCKET_CONNECT_TIMEOUT: "5"
  
  # Rate limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_DEFAULT: "200/minute"
  RATE_LIMIT_AUTH: "10/minute"
  
  # Session settings
  SESSION_LIFETIME: "7200"  # 2 hours
  SESSION_REFRESH_LIFETIME: "2592000"  # 30 days
  
  # File upload
  MAX_UPLOAD_SIZE: "104857600"  # 100MB
  ALLOWED_EXTENSIONS: ".pdf,.docx,.txt,.md"
  
  # Agent execution
  AGENT_TIMEOUT: "300"  # 5 minutes
  MAX_CONCURRENT_AGENTS: "5"
  
  # Quality settings
  QUALITY_THRESHOLD: "0.6"
  ENABLE_AUTO_REVIEW: "false"
  
  # Monitoring
  METRICS_ENABLED: "true"
  TRACING_ENABLED: "true"
  TRACING_SAMPLE_RATE: "1.0"
